### ISSUE TITLE
OSS platform and closed-source(kind of)

### ISSUE THREAD

**Issue by spreedated** [fpaezf/CS2-rcon-tool#11]
Just curious why you're abusing an OSS platform for your "closed-source".
Actually the question is "why are you not sharing your code?"

However, as nobody has told you, every .NET project is open-source by itself, so having the binaries you can decompile the code, since .NET is partially interpreted.
But again, what is the reason not providing us with the code? Is it because it's as horrible as this code-snippet from "CS2RCONTool.exe" -> File "Settings"

```csharp
switch (num1 > -2 ? num1 : 1)
        {
          case 1:
            int num4 = num2 + 1;
            num2 = 0;
            switch (num4)
            {
              case 1:
                goto label_2;
              case 2:
                goto label_3;
              case 3:
                goto label_4;
              case 4:
                goto label_5;
              case 5:
                goto label_6;
              case 6:
                goto label_7;
              case 7:
                goto label_8;
              case 8:
                goto label_9;
              case 9:
                goto label_10;
              case 10:
                goto label_11;
              case 11:
                goto label_19;
            }
            break;
        }
```

**Comment by fpaezf** [comment]
Hi! Thanks for taking the trouble to write to me.

Basically, I do it because I can and because I feel like it, and I don't have to justify myself to every open-source geek who comes to bore me with their crappy speech.

At no point did I say I was a professional programmer, I'm just someone who's passionate about programming and has created software to manage their own servers, and I'm sharing it with others, nothing more, without any pretense.

Download IlSpy and decompile the code however you like, and create your own professional tool with super clean and structured code... oh wait, you're here bothering me instead.

All the info and source code i used to create this tool is on GitHub and StackOverflow, go find it yourself!.

I have nothing more to say, go bother someone else.
